#!/bin/bash
# GitHub Setup Script
# Replace YOUR_USERNAME with your actual GitHub username

echo "🚀 Setting up GitHub repository..."
echo ""
echo "After creating your repository on GitHub, run these commands:"
echo ""
echo "1. Add your repository as remote (replace YOUR_USERNAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/discuss-forum.git"
echo ""
echo "2. Push your code to GitHub:"
echo "   git push -u origin main"
echo ""
echo "3. Verify the push:"
echo "   git remote -v"
echo ""
echo "📋 Repository Details to Use:"
echo "   Name: discuss-forum"
echo "   Description: A modern forum application with emoji reactions, GIF support, and real-time discussions built with Next.js 15, Prisma, and NextAuth"
echo "   Visibility: Public (recommended for portfolios)"
echo ""
echo "✅ Your project includes:"
echo "   - ✅ Advanced emoji reaction system"
echo "   - ✅ GIF support in comments"
echo "   - ✅ Delete functionality"
echo "   - ✅ Clean comment creation UX"
echo "   - ✅ GitHub authentication"
echo "   - ✅ Responsive design"
echo "   - ✅ Deployment ready configuration"
